---
- hosts: cloudcontroller:clouds
  become: true
  tasks:
    - name: Create dev tools file
      shell: |
        cat > "/home/{{ username }}/install_dev_tools.py" <<EOF
        import subprocess
        import os
        subprocess.run("sudo apt install zsh neovim tree -y", shell=True)
        subprocess.run("mkdir -p ~/.config/nvim/pack/tpope/start", shell=True)
        subprocess.run("git clone https://github.com/tpope/vim-surround.git ~/.config/nvim/pack/tpope/start/vim-surround", shell=True)
        subprocess.run("git clone https://github.com/tpope/vim-commentary.git ~/.config/nvim/pack/tpope/start/vim-commentary", shell=True)
        subprocess.run("git clone https://github.com/tpope/vim-unimpaired.git ~/.config/nvim/pack/tpope/start/vim-unimpaired", shell=True)
        subprocess.run("git clone https://github.com/tpope/vim-repeat.git ~/.config/nvim/pack/tpope/start/vim-repeat", shell=True)
        subprocess.run("git clone https://github.com/tpope/vim-eunuch.git ~/.config/nvim/pack/tpope/start/vim-eunuch", shell=True)
        f_path = os.path.expanduser('.config/nvim/init.vim')
        with open(f_path, "w") as f:
            f.write("""
        set number t_Co=256 scrolloff=7 ts=4 sts=4 sw=4 expandtab nowrap ignorecase smartcase
        filetype on
        syntax enable
        autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
        let mapleader = ","
        noremap \ ,
        nnoremap <Leader>w :w!<CR>
        nnoremap <Leader>q :q<CR>
        nmap <C-j> <C-W>j
        nmap <C-k> <C-W>k
        nmap <C-h> <C-W>h
        nmap <C-l> <C-W>l
        nnoremap <silent> <esc> :silent noh<CR>
        command! W execute 'w !sudo tee % > /dev/null' <bar> edit!
        augroup highlight_yank
            autocmd!
            au TextYankPost * silent! lua vim.highlight.on_yank { higroup='IncSearch', timeout=250 }
        augroup END
        tnoremap <ESC> <C-\><C-n>
        tnoremap <C-v><ESC> <ESC>
        """)
        subprocess.run('wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh', shell=True)
        subprocess.run('chmod +x install.sh', shell=True)
        EOF

        cat > "/home/{{ username }}/.bash_history" <<EOF
        python3.8 install_dev_tools.py
        ./install.sh
        EOF

    - name: create extra dev files
      shell: |
        cat > "/home/{{ username }}/configure_zsh.sh" <<EOF
        #!/bin/bash
        sed -i 's/plugins=(git)/plugins=(git sudo colored-man-pages)/' ~/.zshrc
        sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="pmcgee"/' ~/.zshrc
        EOF
        chmod +x "/home/{{ username }}/configure_zsh.sh"
