---
- hosts: clouds
  become: true
  tasks:
    - name: Run Mosquitto
      command: mosquitto -d -p 1883

    - name: Forward IPv4 and let iptables see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF

        sudo modprobe overlay
        sudo modprobe br_netfilter

        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF

        sudo sysctl --system

    - name: Wait for join command to be finished on cloud controller
      local_action:
        module: wait_for
        path: "{{ continuum_home }}/join-command.txt"
      become: false

    - name: Copy the join command to the cloud node
      copy:
        src: "{{ continuum_home }}/join-command.txt"
        dest: /tmp/join-command.txt

    - name: Make the join command file executable
      file:
        dest: /tmp/join-command.txt
        mode: +x

    - name: Add ignore errors flag
      command: sed -i '${s/$/ --ignore-preflight-errors all/}' /tmp/join-command.txt

    - name: Execute the join command
      shell: bash /tmp/join-command.txt

    - name: Remove unneeded KubeEdge join command file
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/join-command.txt

    # - name: Install kata (QEMU)
    #   shell: |
    #     wget https://github.com/kata-containers/kata-containers/releases/download/3.1.3/kata-static-3.1.3-x86_64.tar.xz
    #     xzcat kata-static-3.1.3-x86_64.tar.xz | sudo tar -xvf - -C /
    #     sudo ln -s /opt/kata/bin/kata-runtime /usr/local/bin
    #     rm kata-static-3.1.3-x86_64.tar.xz

    #     file_path='/etc/containerd/config.toml'

    #     echo '#!/bin/bash' | sudo tee -a /usr/local/bin/containerd-shim-kata-v2 > /dev/null
    #     echo 'KATA_CONF_FILE=/opt/kata/share/defaults/kata-containers/configuration-qemu.toml /opt/kata/bin/containerd-shim-kata-v2 $@' | sudo tee -a /usr/local/bin/containerd-shim-kata-v2 > /dev/null

    #     sudo chmod +x /usr/local/bin/containerd-shim-kata-v2

    #     line_number=$(grep -n 'containerd.runtimes]' "$file_path" | cut -d ":" -f 1)

    #     sed -i "$((line_number + 1)) a\         [plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.kata]" "$file_path"
    #     sed -i "$((line_number + 2)) a\           runtime_type = \"io.containerd.kata.v2\"\n" "$file_path"

    #     sudo systemctl restart containerd

    - name: Install kata-fc
      shell: |
        wget https://github.com/kata-containers/kata-containers/releases/download/3.1.3/kata-static-3.1.3-x86_64.tar.xz
        xzcat kata-static-3.1.3-x86_64.tar.xz | sudo tar -xvf - -C /
        sudo ln -s /opt/kata/bin/kata-runtime /usr/local/bin
        rm kata-static-3.1.3-x86_64.tar.xz

        sudo mkdir -p /var/lib/containerd/io.containerd.snapshotter.v1.devmapper

        sudo touch /var/lib/containerd/io.containerd.snapshotter.v1.devmapper/data
        sudo truncate -s 1G /var/lib/containerd/io.containerd.snapshotter.v1.devmapper/data

        sudo touch /var/lib/containerd/io.containerd.snapshotter.v1.devmapper/meta
        sudo truncate -s 1G /var/lib/containerd/io.containerd.snapshotter.v1.devmapper/meta

        DATA_DEV=$(sudo losetup --find --show /var/lib/containerd/io.containerd.snapshotter.v1.devmapper/data)
        META_DEV=$(sudo losetup --find --show /var/lib/containerd/io.containerd.snapshotter.v1.devmapper/meta)

        DATA_SIZE="$(sudo blockdev --getsize64 -q ${DATA_DEV})"
        LENGTH_IN_SECTORS=$((DATA_SIZE / 512))

        sudo dmsetup create devpool --table "0 ${LENGTH_IN_SECTORS} thin-pool ${META_DEV} ${DATA_DEV} 128 32768"

        file_path='/etc/containerd/config.toml'

        line_number=$(grep -n 'io.containerd.snapshotter.v1.devmapper' "$file_path" | cut -d ":" -f 1)

        sudo sed -i "$((line_number + 1)) c\    pool_name = \"devpool\"" "$file_path"
        sudo sed -i "$((line_number + 2)) c\    root_path = \"/var/lib/containerd/io.containerd.snapshotter.v1.devmapper\"" "$file_path"
        sudo sed -i "$((line_number + 3)) c\    base_image_size = \"1GB\"" "$file_path"
        sudo sed -i "$((line_number + 4)) c\    discard_blocks = true" "$file_path"

        sudo sed -i 's/snapshotter = "overlayfs"/snapshotter = "devmapper"/g' "$file_path"

        echo '#!/bin/bash' | sudo tee -a /usr/local/bin/containerd-shim-kata-fc-v2 > /dev/null
        echo 'KATA_CONF_FILE=/opt/kata/share/defaults/kata-containers/configuration-fc.toml /opt/kata/bin/containerd-shim-kata-v2 $@' | sudo tee -a /usr/local/bin/containerd-shim-kata-fc-v2 > /dev/null

        sudo chmod +x /usr/local/bin/containerd-shim-kata-fc-v2

        line_number=$(grep -n 'containerd.runtimes]' "$file_path" | cut -d ":" -f 1)

        sed -i "$((line_number + 1)) a\         [plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.kata-fc]" "$file_path"
        sed -i "$((line_number + 2)) a\           runtime_type = \"io.containerd.kata-fc.v2\"\n" "$file_path"

        sudo systemctl restart containerd

    - name: Create dev tools file
      shell: |
        cat > "/home/{{ username }}/install_dev_tools.py" <<EOF
        import subprocess
        import os
        def my_tools():
            subprocess.run("sudo apt install zsh neovim tree -y", shell=True)
            subprocess.run("mkdir -p ~/.config/nvim/pack/tpope/start", shell=True)
            subprocess.run("git clone https://github.com/tpope/vim-surround.git ~/.config/nvim/pack/tpope/start/vim-surround", shell=True)
            subprocess.run("git clone https://github.com/tpope/vim-commentary.git ~/.config/nvim/pack/tpope/start/vim-commentary", shell=True)
            subprocess.run("git clone https://github.com/tpope/vim-unimpaired.git ~/.config/nvim/pack/tpope/start/vim-unimpaired", shell=True)
            subprocess.run("git clone https://github.com/tpope/vim-repeat.git ~/.config/nvim/pack/tpope/start/vim-repeat", shell=True)
            subprocess.run("git clone https://github.com/tpope/vim-eunuch.git ~/.config/nvim/pack/tpope/start/vim-eunuch", shell=True)
            f_path = os.path.expanduser('.config/nvim/init.vim')
            with open(f_path, "w") as f:
                f.write("""
        set number t_Co=256 scrolloff=7 ts=4 sts=4 sw=4 expandtab nowrap ignorecase smartcase
        filetype on
        syntax enable
        autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
        let mapleader = ","
        noremap \ ,
        nnoremap <Leader>w :w!<CR>
        nnoremap <Leader>q :q<CR>
        nmap <C-j> <C-W>j
        nmap <C-k> <C-W>k
        nmap <C-h> <C-W>h
        nmap <C-l> <C-W>l
        nnoremap <silent> <esc> :silent noh<CR>
        command! W execute 'w !sudo tee % > /dev/null' <bar> edit!
        augroup highlight_yank
            autocmd!
            au TextYankPost * silent! lua vim.highlight.on_yank { higroup='IncSearch', timeout=250 }
        augroup END
        tnoremap <ESC> <C-\><C-n>
        tnoremap <C-v><ESC> <ESC>
        """)
            subprocess.run('wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh', shell=True)
        if __name__ == '__main__':
            my_tools()
        EOF
        chmod +x install.sh
        cat > "/home/{{ username }}/.bash_history" <<EOF
        python3.8 install_dev_tools.py
        ./install.sh
        EOF

    - name: Install tracing tools
      shell: |
        sudo snap install docker

    - name: create resetTracesFile
      shell: |
        cat > "/home/{{ username }}/resetTraces.sh" <<EOF
        #!/bin/bash
        sudo docker stop "$(sudo docker ps -aq)"
        sudo docker rm "$(sudo docker ps -aq)"
        sudo docker run -d --name jaeger \
          -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
          -e COLLECTOR_OTLP_ENABLED=true \
          -p 6831:6831/udp \
          -p 6832:6832/udp \
          -p 5778:5778 \
          -p 16686:16686 \
          -p 4317:4317 \
          -p 4318:4318 \
          -p 14250:14250 \
          -p 14268:14268 \
          -p 14269:14269 \
          -p 9411:9411 \
          jaegertracing/all-in-one:1.47
        EOF
        chmod +x "/home/{{ username }}/resetTraces.sh"

    - name: create extra files
      shell: |
        cat > "/home/{{ username }}/kata-fc.sh" <<EOF
        #!/bin/bash
        sudo sed -i 's/snapshotter = "overlayfs"/snapshotter = "devmapper"/g' /etc/containerd/config.toml
        sudo systemctl restart containerd
        EOF
        chmod +x "/home/{{ username }}/kata-fc.sh"
        cat > "/home/{{ username }}/kata-qemu.sh" <<EOF
        #!/bin/bash
        sudo sed -i 's/snapshotter = "devmapper"/snapshotter = "overlayfs"/g' /etc/containerd/config.toml
        sudo systemctl restart containerd
        EOF
        chmod +x "/home/{{ username }}/kata-qemu.sh"
