---
- hosts: clouds
  become: true
  tasks:
    - name: Install tracing tools
      command: sudo snap install docker

    - name: Ensure Docker service is started
      service:
        name: snap.docker.dockerd.service
        state: started
        enabled: yes

    - name: start tracing daemon
      shell: |
        sudo docker run -d --name jaeger \
          -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
          -e COLLECTOR_OTLP_ENABLED=true \
          -p 6831:6831/udp \
          -p 6832:6832/udp \
          -p 5778:5778 \
          -p 16686:16686 \
          -p 4317:4317 \
          -p 4318:4318 \
          -p 14250:14250 \
          -p 14268:14268 \
          -p 14269:14269 \
          -p 9411:9411 \
          jaegertracing/all-in-one:1.47 --query.max-clock-skew-adjustment=20s

    - name: create resetTracesFile
      shell: |
        cat > "/home/{{ username }}/resetTraces.sh" <<EOF
        #!/bin/bash
        sudo docker stop "\$(sudo docker ps -aq)"
        sudo docker rm "\$(sudo docker ps -aq)"
        sudo docker run -d --name jaeger \
          -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
          -e COLLECTOR_OTLP_ENABLED=true \
          -p 6831:6831/udp \
          -p 6832:6832/udp \
          -p 5778:5778 \
          -p 16686:16686 \
          -p 4317:4317 \
          -p 4318:4318 \
          -p 14250:14250 \
          -p 14268:14268 \
          -p 14269:14269 \
          -p 9411:9411 \
          jaegertracing/all-in-one:1.47 --query.max-clock-skew-adjustment=20s
        EOF
        chmod +x "/home/{{ username }}/resetTraces.sh"
